### ISSUE TITLE
default repository opam 2.2.0 alpha

### ISSUE THREAD

**Issue by biloute02** [ocaml/platform-blog#95]
Hi,

In the opam 2.2.0 alpha blog posts, in the section "How to Test opam on Windows", the command :
`opam init https://github.com/ocaml-opam/opam-repository-mingw`
gives an error

It should probably be :
`opam init https://github.com/ocaml-opam/opam-repository-mingw.git`

It will save time for some

Best regards

**Comment by kit-ty-kate** [comment]
Fixed in https://github.com/ocaml/platform-blog/commit/fae09fbb7290b715d9031479fb2964f4af1ed221

Thanks a lot for the report. The website should be updated in less than 4 hours
